version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: .docker/web.docker
    volumes:
      - ./:/var/www:delegated
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: .docker/app.docker
    env_file: .env
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www:delegated
      #- ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal log=/tmp/xdebug.log"
      PHP_IDE_CONFIG: serverName=Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - mysql

  mysql:
    build:
      context: ./
      dockerfile: .docker/mysql.docker
    command: --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret123
    ports:
      - 3306:3306
    volumes:
      - my-datavolume:/var/lib/mysql
      - .docker/init.sql:/data/application/init.sql

volumes:
  my-datavolume:
